#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import pc from 'picocolors';
import crypto from 'crypto';

const DEFAULT_ENDPOINT = 'https://license-tau-nine.vercel.app';

// ─────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────
type Framework = 'nextjs' | 'react' | 'vue' | 'unknown';

function detectFramework(cwd: string): Framework {
  const pkgPath = path.join(cwd, 'package.json');
  if (!fs.existsSync(pkgPath)) return 'unknown';
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (deps['next']) return 'nextjs';
    if (deps['vue']) return 'vue';
    if (deps['react']) return 'react';
  } catch { /* ignore */ }
  return 'unknown';
}

function generateApiKey(): string {
  return 'LG-' + crypto.randomBytes(24).toString('hex');
}

function prompt(question: string): Promise<string> {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    rl.question(question, answer => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

// ─────────────────────────────────────────────────────────
// Auto-Setup: Create lib/license-guard.ts + inject import
// ─────────────────────────────────────────────────────────
function setupFrameworkFiles(cwd: string, framework: Framework, apiKey: string, endpoint: string): string[] {
  const lines: string[] = [];

  const libContent = `// ⚡ Auto-generated by @masdannn/license-guard — JANGAN DIHAPUS
import { initGuard } from '@masdannn/license-guard';

if (typeof window !== 'undefined') {
  initGuard({
    apiKey: '${apiKey}',
    endpoint: '${endpoint}',
  });
}
`;

  if (framework === 'nextjs') {
    let libDir = path.join(cwd, 'lib');
    if (!fs.existsSync(libDir)) fs.mkdirSync(libDir, { recursive: true });
    fs.writeFileSync(path.join(libDir, 'license-guard.ts'), libContent, 'utf-8');
    lines.push(`  ${pc.green('✅')} Dibuat: ${pc.bold('lib/license-guard.ts')}`);

    // Inject ke app/layout.tsx atau pages/_app.tsx
    const candidates = [
      { file: path.join(cwd, 'app', 'layout.tsx'), importLine: "import '@/lib/license-guard';" },
      { file: path.join(cwd, 'app', 'layout.jsx'), importLine: "import '@/lib/license-guard';" },
      { file: path.join(cwd, 'pages', '_app.tsx'), importLine: "import '@/lib/license-guard';" },
      { file: path.join(cwd, 'pages', '_app.jsx'), importLine: "import '@/lib/license-guard';" },
    ];
    let injected = false;
    for (const { file, importLine } of candidates) {
      if (fs.existsSync(file)) {
        const content = fs.readFileSync(file, 'utf-8');
        if (!content.includes('license-guard')) {
          fs.writeFileSync(file, importLine + '\n' + content, 'utf-8');
          lines.push(`  ${pc.green('✅')} Import ditambahkan ke: ${pc.bold(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        } else {
          lines.push(`  ${pc.yellow('⚠️')}  ${pc.bold(path.relative(cwd, file).replace(/\\/g, '/'))} sudah ada import (dilewati)`);
        }
        injected = true;
        break;
      }
    }
    if (!injected) {
      lines.push(`  ${pc.yellow('⚠️')}  Tambahkan manual di root component:`);
      lines.push(`     ${pc.cyan("import '@/lib/license-guard';")}`);
    }

  } else if (framework === 'react' || framework === 'vue') {
    let libDir = path.join(cwd, 'src', 'lib');
    if (!fs.existsSync(libDir)) fs.mkdirSync(libDir, { recursive: true });
    fs.writeFileSync(path.join(libDir, 'license-guard.ts'), libContent, 'utf-8');
    lines.push(`  ${pc.green('✅')} Dibuat: ${pc.bold('src/lib/license-guard.ts')}`);

    const candidates = framework === 'react'
      ? [path.join(cwd, 'src', 'main.tsx'), path.join(cwd, 'src', 'main.jsx'), path.join(cwd, 'src', 'App.tsx')]
      : [path.join(cwd, 'src', 'main.ts'), path.join(cwd, 'src', 'main.js')];

    const importLine = "import './lib/license-guard';";
    let injected = false;
    for (const file of candidates) {
      if (fs.existsSync(file)) {
        const content = fs.readFileSync(file, 'utf-8');
        if (!content.includes('license-guard')) {
          fs.writeFileSync(file, importLine + '\n' + content, 'utf-8');
          lines.push(`  ${pc.green('✅')} Import ditambahkan ke: ${pc.bold(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        } else {
          lines.push(`  ${pc.yellow('⚠️')}  ${pc.bold(path.relative(cwd, file).replace(/\\/g, '/'))} sudah ada import (dilewati)`);
        }
        injected = true;
        break;
      }
    }
    if (!injected) {
      lines.push(`  ${pc.yellow('⚠️')}  Tambahkan manual di ${pc.bold('src/main.ts')}:`);
      lines.push(`     ${pc.cyan(importLine)}`);
    }

  } else {
    lines.push(`  ${pc.yellow('⚠️')}  Framework tidak terdeteksi.`);
    lines.push(`  Tambahkan manual di root aplikasi Anda:`);
    lines.push(`     ${pc.cyan(`import { initGuard } from '@masdannn/license-guard';`)}`);
    lines.push(`     ${pc.cyan(`initGuard({ apiKey: '${apiKey}' });`)}`);
  }

  return lines;
}

// ─────────────────────────────────────────────────────────
// Main CLI
// ─────────────────────────────────────────────────────────
async function main() {
  const cwd = process.cwd();
  const endpoint = process.env.LICENSE_GUARD_SERVER || DEFAULT_ENDPOINT;
  const framework = detectFramework(cwd);

  const frameworkLabel: Record<Framework, string> = {
    nextjs: 'Next.js',
    react: 'React',
    vue: 'Vue',
    unknown: 'Unknown',
  };

  console.clear();
  console.log(pc.bold(pc.green('\n  🛡️  LICENSE GUARD — SETUP')));
  console.log(pc.dim('  ────────────────────────────────────────────────────────'));
  console.log(`  Framework : ${pc.cyan(frameworkLabel[framework])}`);
  console.log(`  Directory : ${pc.dim(cwd)}\n`);

  // ── Cek apakah sudah pernah di-setup ──
  const configPath = path.join(cwd, '.licenseguard.json');
  if (fs.existsSync(configPath)) {
    try {
      const existing = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
      console.log(pc.yellow(`  ⚠️  Project sudah terdaftar sebelumnya:`));
      console.log(`     Project ID : ${pc.bold(existing.projectId)}`);
      console.log(`     Domain     : ${pc.bold(existing.domain)}`);
      console.log(`     API Key    : ${pc.dim(existing.apiKey)}\n`);
      const overwrite = await prompt(pc.yellow('  Ingin daftarkan ulang? (y/N): '));
      if (overwrite.toLowerCase() !== 'y') {
        console.log(pc.dim('\n  Setup dibatalkan.\n'));
        process.exit(0);
      }
      console.log('');
    } catch { /* lanjut */ }
  }

  // ── Input nama project & domain ──
  const name = await prompt(pc.white('  Nama project  : '));
  if (!name) { console.error(pc.red('  ❌ Nama project tidak boleh kosong.')); process.exit(1); }

  const domain = await prompt(pc.white('  Domain website: '));
  if (!domain) { console.error(pc.red('  ❌ Domain tidak boleh kosong.')); process.exit(1); }

  console.log(pc.dim('\n  ────────────────────────────────────────────────────────'));
  console.log(pc.yellow('  ⏳ Mendaftarkan project ke Control Hub...'));

  // ── Generate API Key di sisi klien ──
  const apiKey = generateApiKey();

  try {
    const res = await fetch(`${endpoint}/api/pairing/init`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name,
        domain,
        apiKey,
        framework: frameworkLabel[framework],
      }),
    });

    const data = await res.json();

    if (!res.ok || !data.success) {
      console.error(pc.red(`\n  ❌ Gagal mendaftarkan: ${data.error || 'Server error'}`));
      process.exit(1);
    }

    // ── Simpan .licenseguard.json ──
    const configData = {
      projectId: data.projectId,
      apiKey,
      domain: data.domain,
      name: data.name,
      endpoint,
      framework: frameworkLabel[framework],
      registeredAt: new Date().toISOString(),
    };
    fs.writeFileSync(configPath, JSON.stringify(configData, null, 2), 'utf-8');

    // ── Setup file integrasi ──
    console.log(pc.bold('\n  ⚡ Setup Otomatis:'));
    const setupLines = setupFrameworkFiles(cwd, framework, apiKey, endpoint);
    setupLines.forEach(l => console.log(l));
    console.log(`  ${pc.green('✅')} Config: ${pc.bold('.licenseguard.json')}`);

    // ── Hasil akhir ──
    console.log(pc.dim('\n  ────────────────────────────────────────────────────────'));
    console.log(pc.bold(pc.green('  ✅ SETUP SELESAI — PROJECT TERDAFTAR & AKTIF!\n')));
    console.log(`  Project   : ${pc.bold(data.name)}`);
    console.log(`  Domain    : ${pc.bold(data.domain)}`);
    console.log(`  Status    : ${pc.green('● ACTIVE')}`);
    console.log(`  API Key   : ${pc.dim(apiKey)}`);
    console.log(`  Dashboard : ${pc.cyan(`${endpoint}/projects/${data.projectId}`)}\n`);
    console.log(pc.dim('  Admin dapat mengecek status koneksi di dashboard di atas.'));
    console.log(pc.bold(pc.green('\n  🛡️  Website Anda kini terlindungi oleh License Guard!\n')));

    process.exit(0);
  } catch (err) {
    console.error(pc.red(`\n  ❌ Gagal terhubung ke server: ${err instanceof Error ? err.message : err}`));
    process.exit(1);
  }
}

main();
