#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import pc from 'picocolors';
import crypto from 'crypto';

const DEFAULT_ENDPOINT = 'https://license-tau-nine.vercel.app';

type Framework = 'nextjs' | 'react' | 'vue' | 'unknown';

function detectFramework(cwd: string): Framework {
  const pkgPath = path.join(cwd, 'package.json');
  if (!fs.existsSync(pkgPath)) return 'unknown';
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (deps['next']) return 'nextjs';
    if (deps['vue']) return 'vue';
    if (deps['react']) return 'react';
  } catch { /* ignore */ }
  return 'unknown';
}

function generateApiKey(): string {
  return 'LG-' + crypto.randomBytes(24).toString('hex');
}

function createPromptHelper() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const ask = (query: string): Promise<string> => {
    return new Promise(resolve => {
      rl.question(query, answer => {
        resolve(answer.trim());
      });
    });
  };

  const close = () => {
    rl.close();
  };

  return { ask, close };
}

function setupFrameworkFiles(cwd: string, framework: Framework, apiKey: string, endpoint: string): string[] {
  const lines: string[] = [];

  const libContent = `// ⚡ Auto-generated by @masdannn/license-guard — JANGAN DIHAPUS
import { initGuard } from '@masdannn/license-guard';

if (typeof window !== 'undefined') {
  initGuard({
    apiKey: '${apiKey}',
    endpoint: '${endpoint}',
  });
}
`;

  if (framework === 'nextjs') {
    const libDir = path.join(cwd, 'lib');
    if (!fs.existsSync(libDir)) fs.mkdirSync(libDir, { recursive: true });
    fs.writeFileSync(path.join(libDir, 'license-guard.ts'), libContent, 'utf-8');
    lines.push(`  ${pc.green('✓')} Dibuat: ${pc.bold('lib/license-guard.ts')}`);

    const candidates = [
      { file: path.join(cwd, 'app', 'layout.tsx'), importLine: "import '@/lib/license-guard';" },
      { file: path.join(cwd, 'app', 'layout.jsx'), importLine: "import '@/lib/license-guard';" },
      { file: path.join(cwd, 'pages', '_app.tsx'), importLine: "import '@/lib/license-guard';" },
      { file: path.join(cwd, 'pages', '_app.jsx'), importLine: "import '@/lib/license-guard';" },
    ];
    let injected = false;
    for (const { file, importLine } of candidates) {
      if (fs.existsSync(file)) {
        const content = fs.readFileSync(file, 'utf-8');
        if (!content.includes('license-guard')) {
          fs.writeFileSync(file, importLine + '\n' + content, 'utf-8');
          lines.push(`  ${pc.green('✓')} Import ditambahkan ke: ${pc.bold(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        } else {
          lines.push(`  ${pc.dim('·')} Import sudah ada di: ${pc.dim(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        }
        injected = true;
        break;
      }
    }
    if (!injected) {
      lines.push(`  ${pc.yellow('!')} Tambahkan manual di root component: ${pc.cyan("import '@/lib/license-guard';")}`);
    }

  } else if (framework === 'react' || framework === 'vue') {
    const libDir = path.join(cwd, 'src', 'lib');
    if (!fs.existsSync(libDir)) fs.mkdirSync(libDir, { recursive: true });
    fs.writeFileSync(path.join(libDir, 'license-guard.ts'), libContent, 'utf-8');
    lines.push(`  ${pc.green('✓')} Dibuat: ${pc.bold('src/lib/license-guard.ts')}`);

    const candidates = framework === 'react'
      ? [path.join(cwd, 'src', 'main.tsx'), path.join(cwd, 'src', 'main.jsx'), path.join(cwd, 'src', 'App.tsx')]
      : [path.join(cwd, 'src', 'main.ts'), path.join(cwd, 'src', 'main.js')];

    const importLine = "import './lib/license-guard';";
    let injected = false;
    for (const file of candidates) {
      if (fs.existsSync(file)) {
        const content = fs.readFileSync(file, 'utf-8');
        if (!content.includes('license-guard')) {
          fs.writeFileSync(file, importLine + '\n' + content, 'utf-8');
          lines.push(`  ${pc.green('✓')} Import ditambahkan ke: ${pc.bold(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        } else {
          lines.push(`  ${pc.dim('·')} Import sudah ada di: ${pc.dim(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        }
        injected = true;
        break;
      }
    }
    if (!injected) {
      lines.push(`  ${pc.yellow('!')} Tambahkan manual di ${pc.bold('src/main.ts')}: ${pc.cyan(importLine)}`);
    }

  } else {
    lines.push(`  ${pc.yellow('!')} Tambahkan manual di root aplikasi:`);
    lines.push(`     ${pc.cyan(`import { initGuard } from '@masdannn/license-guard';`)}`);
    lines.push(`     ${pc.cyan(`initGuard({ apiKey: '${apiKey}' });`)}`);
  }

  return lines;
}

async function main() {
  const cwd = process.cwd();
  const endpoint = process.env.LICENSE_GUARD_SERVER || DEFAULT_ENDPOINT;
  const framework = detectFramework(cwd);

  const frameworkLabel: Record<Framework, string> = {
    nextjs: 'Next.js',
    react: 'React',
    vue: 'Vue',
    unknown: 'Generic / Other',
  };

  console.log(pc.bold(pc.green('\n  🛡️  LICENSE GUARD SETUP')));
  console.log(pc.dim('  ────────────────────────────────────────────────────────'));
  console.log(`  Framework : ${pc.cyan(frameworkLabel[framework])}`);
  console.log(`  Directory : ${pc.dim(cwd)}\n`);

  const prompter = createPromptHelper();

  try {
    const configPath = path.join(cwd, '.licenseguard.json');
    if (fs.existsSync(configPath)) {
      try {
        const existing = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
        console.log(pc.yellow(`  ⚠️  Project sudah pernah di-setup:`));
        console.log(`     Project : ${pc.bold(existing.name || existing.projectId)}`);
        console.log(`     Domain  : ${pc.bold(existing.domain)}\n`);
        const overwrite = await prompter.ask(pc.yellow('  Daftarkan ulang? (y/N): '));
        if (overwrite.toLowerCase() !== 'y') {
          console.log(pc.dim('\n  Setup dibatalkan.\n'));
          prompter.close();
          return;
        }
        console.log('');
      } catch { /* ignore */ }
    }

    const name = await prompter.ask(pc.white('  Nama Project   : '));
    if (!name) {
      console.error(pc.red('\n  ❌ Nama project tidak boleh kosong.\n'));
      prompter.close();
      process.exitCode = 1;
      return;
    }

    const domain = await prompter.ask(pc.white('  Domain Website : '));
    if (!domain) {
      console.error(pc.red('\n  ❌ Domain tidak boleh kosong.\n'));
      prompter.close();
      process.exitCode = 1;
      return;
    }

    prompter.close();

    console.log(pc.dim('\n  ────────────────────────────────────────────────────────'));
    console.log(pc.yellow('  ⏳ Menghubungkan ke Control Hub...'));

    const apiKey = generateApiKey();

    const res = await fetch(`${endpoint}/api/pairing/init`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name,
        domain,
        apiKey,
        framework: frameworkLabel[framework],
      }),
    });

    const data = await res.json();

    if (!res.ok || !data.success) {
      console.error(pc.red(`\n  ❌ Gagal mendaftarkan: ${data.error || 'Server error'}\n`));
      process.exitCode = 1;
      return;
    }

    // Simpan .licenseguard.json
    const configData = {
      projectId: data.projectId,
      apiKey,
      domain: data.domain,
      name: data.name,
      endpoint,
      framework: frameworkLabel[framework],
      registeredAt: new Date().toISOString(),
    };
    fs.writeFileSync(configPath, JSON.stringify(configData, null, 2), 'utf-8');

    console.log(pc.bold('\n  ⚡ Setup Selesai:'));
    const setupLines = setupFrameworkFiles(cwd, framework, apiKey, endpoint);
    setupLines.forEach(l => console.log(l));
    console.log(`  ${pc.green('✓')} Config: ${pc.bold('.licenseguard.json')}`);

    console.log(pc.dim('\n  ────────────────────────────────────────────────────────'));
    console.log(pc.bold(pc.green('  ✅ STATUS: ACTIVE')));
    console.log(`  Project   : ${pc.bold(data.name)}`);
    console.log(`  Domain    : ${pc.bold(data.domain)}`);
    console.log(`  API Key   : ${pc.dim(apiKey)}`);
    console.log(`  Dashboard : ${pc.cyan(`${endpoint}/projects/${data.projectId}`)}`);
    console.log(pc.dim('  ────────────────────────────────────────────────────────\n'));

  } catch (err) {
    prompter.close();
    console.error(pc.red(`\n  ❌ Error: ${err instanceof Error ? err.message : err}\n`));
    process.exitCode = 1;
  }
}

main();
