#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import readline from 'readline';
import pc from 'picocolors';
import crypto from 'crypto';
import { encodeLicensePayload, decodeLicensePayload } from './index';

const DEFAULT_ENDPOINT = 'https://license-tau-nine.vercel.app';
const CURRENT_VERSION = '^1.0.7';

type Framework = 'nextjs' | 'react' | 'vue' | 'unknown';

function detectFramework(cwd: string): Framework {
  const pkgPath = path.join(cwd, 'package.json');
  if (!fs.existsSync(pkgPath)) return 'unknown';
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (deps['next']) return 'nextjs';
    if (deps['vue']) return 'vue';
    if (deps['react']) return 'react';
  } catch { /* ignore */ }
  return 'unknown';
}

function ensurePackageDependency(cwd: string): boolean {
  const pkgPath = path.join(cwd, 'package.json');
  if (!fs.existsSync(pkgPath)) return false;
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
    if (!pkg.dependencies) pkg.dependencies = {};
    pkg.dependencies['@masdannn/license-guard'] = CURRENT_VERSION;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2), 'utf-8');
    return true;
  } catch {
    return false;
  }
}

function generateApiKey(): string {
  return 'LG-' + crypto.randomBytes(24).toString('hex');
}

function createPromptHelper() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const ask = (query: string): Promise<string> => {
    return new Promise(resolve => {
      rl.question(query, answer => {
        resolve(answer.trim());
      });
    });
  };

  const close = () => {
    try {
      rl.close();
      if (process.stdin && typeof process.stdin.pause === 'function') {
        process.stdin.pause();
      }
      if (process.stdin && typeof process.stdin.unref === 'function') {
        process.stdin.unref();
      }
    } catch { /* ignore */ }
  };

  return { ask, close };
}

function setupFrameworkFiles(cwd: string, framework: Framework, encryptedKey: string): string[] {
  const lines: string[] = [];

  // Update/ensure package.json dependency
  if (ensurePackageDependency(cwd)) {
    lines.push(`  ${pc.green('✓')} Dependency: ${pc.bold('@masdannn/license-guard' + CURRENT_VERSION)}`);
  }

  const libContent = `'use client';

// ⚡ Auto-generated by @masdannn/license-guard — JANGAN DIHAPUS
import { initGuard } from '@masdannn/license-guard';

if (typeof window !== 'undefined') {
  initGuard({
    key: '${encryptedKey}',
  });
}
`;

  if (framework === 'nextjs') {
    const libDir = path.join(cwd, 'lib');
    if (!fs.existsSync(libDir)) fs.mkdirSync(libDir, { recursive: true });
    fs.writeFileSync(path.join(libDir, 'license-guard.ts'), libContent, 'utf-8');
    lines.push(`  ${pc.green('✓')} Dibuat: ${pc.bold('lib/license-guard.ts')} (encrypted key)`);

    const candidates = [
      { file: path.join(cwd, 'app', 'layout.tsx'), importLine: "import '@/lib/license-guard';" },
      { file: path.join(cwd, 'app', 'layout.jsx'), importLine: "import '@/lib/license-guard';" },
      { file: path.join(cwd, 'pages', '_app.tsx'), importLine: "import '@/lib/license-guard';" },
      { file: path.join(cwd, 'pages', '_app.jsx'), importLine: "import '@/lib/license-guard';" },
    ];
    let injected = false;
    for (const { file, importLine } of candidates) {
      if (fs.existsSync(file)) {
        const content = fs.readFileSync(file, 'utf-8');
        if (!content.includes('license-guard')) {
          fs.writeFileSync(file, importLine + '\n' + content, 'utf-8');
          lines.push(`  ${pc.green('✓')} Import ditambahkan ke: ${pc.bold(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        } else {
          lines.push(`  ${pc.dim('·')} Import aktif di: ${pc.dim(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        }
        injected = true;
        break;
      }
    }
    if (!injected) {
      lines.push(`  ${pc.yellow('!')} Tambahkan manual di root component: ${pc.cyan("import '@/lib/license-guard';")}`);
    }

  } else if (framework === 'react' || framework === 'vue') {
    const libDir = path.join(cwd, 'src', 'lib');
    if (!fs.existsSync(libDir)) fs.mkdirSync(libDir, { recursive: true });
    fs.writeFileSync(path.join(libDir, 'license-guard.ts'), libContent, 'utf-8');
    lines.push(`  ${pc.green('✓')} Dibuat: ${pc.bold('src/lib/license-guard.ts')} (encrypted key)`);

    const candidates = framework === 'react'
      ? [path.join(cwd, 'src', 'main.tsx'), path.join(cwd, 'src', 'main.jsx'), path.join(cwd, 'src', 'App.tsx')]
      : [path.join(cwd, 'src', 'main.ts'), path.join(cwd, 'src', 'main.js')];

    const importLine = "import './lib/license-guard';";
    let injected = false;
    for (const file of candidates) {
      if (fs.existsSync(file)) {
        const content = fs.readFileSync(file, 'utf-8');
        if (!content.includes('license-guard')) {
          fs.writeFileSync(file, importLine + '\n' + content, 'utf-8');
          lines.push(`  ${pc.green('✓')} Import ditambahkan ke: ${pc.bold(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        } else {
          lines.push(`  ${pc.dim('·')} Import aktif di: ${pc.dim(path.relative(cwd, file).replace(/\\/g, '/'))}`);
        }
        injected = true;
        break;
      }
    }
    if (!injected) {
      lines.push(`  ${pc.yellow('!')} Tambahkan manual di ${pc.bold('src/main.ts')}: ${pc.cyan(importLine)}`);
    }

  } else {
    lines.push(`  ${pc.yellow('!')} Tambahkan manual di root aplikasi:`);
    lines.push(`     ${pc.cyan(`import { initGuard } from '@masdannn/license-guard';`)}`);
    lines.push(`     ${pc.cyan(`initGuard({ key: '${encryptedKey}' });`)}`);
  }

  return lines;
}

// ─────────────────────────────────────────────────────────
// Commands
// ─────────────────────────────────────────────────────────

function printHelp() {
  console.log(pc.bold(pc.green('\n  🛡️  CENTRALIZED LICENSE GUARD CLI')));
  console.log(pc.dim('  ─────────────────────────────────────────────────────────'));
  console.log('  Penggunaan: ' + pc.cyan('npx @masdannn/license-guard [perintah]\n'));
  console.log(pc.bold('  DAFTAR PERINTAH:'));
  console.log(`    ${pc.green('init')}     ${pc.dim('(default)')} Inisialisasi / perbarui pendaftaran project secara otomatis`);
  console.log(`    ${pc.green('view')}     Lihat detail lisensi, status koneksi live di server, dan dashboard`);
  console.log(`    ${pc.green('fix')}      Perbaiki / regenerasi file lib dan import yang hilang`);
  console.log(`    ${pc.green('new')}      Daftarkan ulang dengan API Key baru (Reset Kredensial)`);
  console.log(`    ${pc.green('test')}     Uji konektivitas heartbeat langsung ke server`);
  console.log(`    ${pc.green('--help')}   Tampilkan panduan bantuan ini`);
  console.log(pc.dim('\n  ─────────────────────────────────────────────────────────'));
  console.log(pc.dim('  Dokumentasi: https://license-tau-nine.vercel.app/settings\n'));
}

async function handleView(cwd: string) {
  const configPath = path.join(cwd, '.licenseguard.json');
  if (!fs.existsSync(configPath)) {
    console.log(pc.red('\n  ❌ File konfigurasi .licenseguard.json tidak ditemukan.'));
    console.log(pc.yellow('  Jalankan: npx @masdannn/license-guard init\n'));
    return;
  }

  try {
    const raw = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    const key = raw.licenseKey || raw.apiKey;
    const decoded = raw.licenseKey ? decodeLicensePayload(raw.licenseKey) : { apiKey: raw.apiKey, endpoint: raw.endpoint };
    const endpoint = decoded.endpoint || raw.endpoint || DEFAULT_ENDPOINT;

    console.log(pc.bold(pc.green('\n  🛡️  INFORMASI LISENSI INSTANCE')));
    console.log(pc.dim('  ─────────────────────────────────────────────────────────'));
    console.log(`  Project ID : ${pc.bold(raw.projectId || '—')}`);
    console.log(`  Name       : ${pc.bold(raw.name || '—')}`);
    console.log(`  Domain     : ${pc.bold(raw.domain || '—')}`);
    console.log(`  Framework  : ${pc.cyan(raw.framework || 'Unknown')}`);
    console.log(`  Key Token  : ${pc.dim((key || '').slice(0, 24) + '...')}`);
    console.log(`  Dashboard  : ${pc.cyan(`${endpoint}/projects/${raw.projectId || ''}`)}`);
    console.log(pc.dim('  ─────────────────────────────────────────────────────────'));

    console.log(pc.yellow('  ⏳ Mengecek status live di server...'));
    const res = await fetch(`${endpoint}/api/license/heartbeat`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ apiKey: decoded.apiKey, domain: raw.domain }),
    });

    if (res.status === 200) {
      console.log(`  Live Status: ${pc.green('● ACTIVE (Terhubung & Terlindungi)')}\n`);
    } else {
      console.log(`  Live Status: ${pc.red('■ SUSPENDED / LOCKED')}\n`);
    }
  } catch (err) {
    console.error(pc.red(`\n  ❌ Gagal membaca info: ${err instanceof Error ? err.message : err}\n`));
  }
}

async function handleFix(cwd: string) {
  const configPath = path.join(cwd, '.licenseguard.json');
  if (!fs.existsSync(configPath)) {
    console.log(pc.red('\n  ❌ Tidak ada file .licenseguard.json.'));
    console.log(pc.yellow('  Jalankan setup baru: npx @masdannn/license-guard init\n'));
    return;
  }

  const raw = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
  const framework = detectFramework(cwd);
  const endpoint = raw.endpoint || DEFAULT_ENDPOINT;
  const apiKey = raw.apiKey || (raw.licenseKey ? decodeLicensePayload(raw.licenseKey).apiKey : '');

  const encryptedKey = encodeLicensePayload({ apiKey, endpoint, domain: raw.domain });

  console.log(pc.bold(pc.green('\n  🔧 MEMPERBAIKI INTEGRASI LICENSE GUARD')));
  console.log(pc.dim('  ─────────────────────────────────────────────────────────'));

  const setupLines = setupFrameworkFiles(cwd, framework, encryptedKey);
  setupLines.forEach(l => console.log(l));

  const updatedConfig = {
    ...raw,
    licenseKey: encryptedKey,
    fixedAt: new Date().toISOString(),
  };
  fs.writeFileSync(configPath, JSON.stringify(updatedConfig, null, 2), 'utf-8');

  console.log(`  ${pc.green('✓')} Config: ${pc.bold('.licenseguard.json')}`);
  console.log(pc.dim('  ─────────────────────────────────────────────────────────'));
  console.log(pc.bold(pc.green('  ✅ Integrasi berhasil diperbaiki & siap digunakan!\n')));
}

async function handleTest(cwd: string) {
  const configPath = path.join(cwd, '.licenseguard.json');
  if (!fs.existsSync(configPath)) {
    console.log(pc.red('\n  ❌ File konfigurasi tidak ditemukan. Jalankan setup terlebih dahulu.\n'));
    return;
  }

  const raw = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
  const decoded = raw.licenseKey ? decodeLicensePayload(raw.licenseKey) : { apiKey: raw.apiKey, endpoint: raw.endpoint };
  const endpoint = decoded.endpoint || raw.endpoint || DEFAULT_ENDPOINT;

  console.log(pc.bold(pc.green('\n  ⚡ TESTING LICENSE GUARD CONNECTION')));
  console.log(pc.dim('  ─────────────────────────────────────────────────────────'));
  console.log(`  Endpoint : ${pc.dim(endpoint)}`);
  console.log(`  Domain   : ${pc.bold(raw.domain || 'localhost')}`);
  console.log(pc.yellow('  ⏳ Mengirim tes heartbeat...'));

  try {
    const res = await fetch(`${endpoint}/api/license/heartbeat`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ apiKey: decoded.apiKey, domain: raw.domain }),
    });

    const data = await res.json();
    console.log(pc.dim('  ─────────────────────────────────────────────────────────'));

    if (res.status === 200 && data.valid) {
      console.log(pc.bold(pc.green('  ✅ KONEKSI BERHASIL — LISENSI VALID & AKTIF')));
      console.log(`  Status      : ${pc.green(data.status)}`);
      console.log(`  Grace Period: ${pc.dim(data.gracePeriod + ' jam')}\n`);
    } else {
      console.log(pc.bold(pc.red('  ❌ LISENSI DINONAKTIFKAN ATAU INVALID')));
      console.log(`  Status      : ${pc.red(data.status || 'SUSPENDED')}`);
      console.log(`  Pesan       : ${pc.yellow(data.error || 'Akses ditangguhkan')}\n`);
    }
  } catch (err) {
    console.error(pc.red(`\n  ❌ Gagal terhubung: ${err instanceof Error ? err.message : err}\n`));
  }
}

async function handleInit(cwd: string) {
  const endpoint = process.env.LICENSE_GUARD_SERVER || DEFAULT_ENDPOINT;
  const framework = detectFramework(cwd);

  const frameworkLabel: Record<Framework, string> = {
    nextjs: 'Next.js',
    react: 'React',
    vue: 'Vue',
    unknown: 'Generic / Other',
  };

  console.log(pc.bold(pc.green('\n  🛡️  LICENSE GUARD SETUP')));
  console.log(pc.dim('  ─────────────────────────────────────────────────────────'));
  console.log(`  Framework : ${pc.cyan(frameworkLabel[framework])}`);
  console.log(`  Directory : ${pc.dim(cwd)}\n`);

  let prevName = '';
  let prevDomain = '';

  const configPath = path.join(cwd, '.licenseguard.json');
  if (fs.existsSync(configPath)) {
    try {
      const existing = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
      prevName = existing.name || '';
      prevDomain = existing.domain || '';
      console.log(pc.dim(`  // Memperbarui konfigurasi yang sudah ada:`));
      if (prevName) console.log(`  // Nama sebelumnya  : ${pc.bold(prevName)}`);
      if (prevDomain) console.log(`  // Domain sebelumnya: ${pc.bold(prevDomain)}\n`);
    } catch { /* ignore */ }
  }

  const prompter = createPromptHelper();

  try {
    const inputName = await prompter.ask(
      prevName
        ? pc.white(`  Nama Project [${prevName}]: `)
        : pc.white('  Nama Project   : ')
    );
    const name = inputName || prevName;
    if (!name) {
      console.error(pc.red('\n  ❌ Nama project tidak boleh kosong.\n'));
      prompter.close();
      process.exitCode = 1;
      return;
    }

    const inputDomain = await prompter.ask(
      prevDomain
        ? pc.white(`  Domain Website [${prevDomain}]: `)
        : pc.white('  Domain Website : ')
    );
    const domain = inputDomain || prevDomain;
    if (!domain) {
      console.error(pc.red('\n  ❌ Domain tidak boleh kosong.\n'));
      prompter.close();
      process.exitCode = 1;
      return;
    }

    prompter.close();

    console.log(pc.dim('\n  ─────────────────────────────────────────────────────────'));
    console.log(pc.yellow('  ⏳ Menghubungkan ke Control Hub...'));

    const apiKey = generateApiKey();

    const res = await fetch(`${endpoint}/api/pairing/init`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name,
        domain,
        apiKey,
        framework: frameworkLabel[framework],
      }),
    });

    const data = await res.json();

    if (!res.ok || !data.success) {
      console.error(pc.red(`\n  ❌ Gagal mendaftarkan: ${data.error || 'Server error'}\n`));
      process.exitCode = 1;
      return;
    }

    // Encrypt payload
    const encryptedKey = encodeLicensePayload({ apiKey, endpoint, domain: data.domain });

    // Simpan .licenseguard.json terenkripsi
    const configData = {
      projectId: data.projectId,
      licenseKey: encryptedKey,
      domain: data.domain,
      name: data.name,
      endpoint,
      framework: frameworkLabel[framework],
      registeredAt: new Date().toISOString(),
    };
    fs.writeFileSync(configPath, JSON.stringify(configData, null, 2), 'utf-8');

    console.log(pc.bold('\n  ⚡ Setup Selesai:'));
    const setupLines = setupFrameworkFiles(cwd, framework, encryptedKey);
    setupLines.forEach(l => console.log(l));
    console.log(`  ${pc.green('✓')} Config: ${pc.bold('.licenseguard.json')} (encrypted)`);

    console.log(pc.dim('\n  ─────────────────────────────────────────────────────────'));
    const statusColor = data.status === 'SUSPENDED' ? pc.red : pc.green;
    console.log(`  Status    : ${statusColor('● ' + data.status)} ${data.status === 'SUSPENDED' ? pc.dim('(dipertahankan)') : ''}`);
    console.log(`  Project   : ${pc.bold(data.name)}`);
    console.log(`  Domain    : ${pc.bold(data.domain)}`);
    console.log(`  Dashboard : ${pc.cyan(`${endpoint}/projects/${data.projectId}`)}`);
    console.log(pc.dim('  ─────────────────────────────────────────────────────────\n'));

  } catch (err) {
    prompter.close();
    console.error(pc.red(`\n  ❌ Error: ${err instanceof Error ? err.message : err}\n`));
    process.exitCode = 1;
  }
}

// ─────────────────────────────────────────────────────────
// Main Entry
// ─────────────────────────────────────────────────────────
async function main() {
  const args = process.argv.slice(2);
  const command = (args[0] || 'init').toLowerCase();
  const cwd = process.cwd();

  switch (command) {
    case 'view':
    case 'status':
    case 'info':
      await handleView(cwd);
      break;

    case 'fix':
    case 'repair':
      await handleFix(cwd);
      break;

    case 'new':
    case 'reset':
    case 'update':
    case 'reinit':
    case 'init':
    default:
      await handleInit(cwd);
      break;

    case 'test':
    case 'check':
      await handleTest(cwd);
      break;

    case '--help':
    case '-h':
    case 'help':
      printHelp();
      break;
  }
}

main();
