/**
 * @masdannn/license-guard — Client SDK Runtime
 * Fully self-contained, offline-resilient & anti-tamper client guard SDK.
 */

export interface LicenseGuardConfig {
  /**
   * Encrypted license payload (generated by CLI) or raw API key
   */
  key?: string;
  apiKey?: string;
  endpoint?: string;
  domain?: string;
  redirect?: string;
  interval?: number; // interval in seconds (default 300)
}

export interface LicenseState {
  valid: boolean;
  status: 'ACTIVE' | 'SUSPENDED' | 'TAMPERED';
  token?: string | null;
  lastCheck?: number;
  suspendedAt?: number | null;
}

const DEFAULT_ENDPOINT = 'https://license-tau-nine.vercel.app';
const STORAGE_KEY = '_lg_guard_state';
const OVERLAY_ID = '__license_guard_lock_overlay__';

/**
 * Reversible obfuscation cipher for client-side credential protection
 */
export function encodeLicensePayload(data: { apiKey: string; endpoint: string; domain?: string }): string {
  const jsonStr = JSON.stringify(data);
  const b64 = typeof Buffer !== 'undefined'
    ? Buffer.from(jsonStr, 'utf-8').toString('base64')
    : btoa(unescape(encodeURIComponent(jsonStr)));
  const obfuscated = b64
    .split('')
    .map((c, i) => String.fromCharCode(c.charCodeAt(0) ^ ((i % 5) + 1)))
    .join('');
  const finalB64 = typeof Buffer !== 'undefined'
    ? Buffer.from(obfuscated, 'binary').toString('base64')
    : btoa(obfuscated);
  return 'LGK_' + finalB64;
}

export function decodeLicensePayload(encoded: string): { apiKey: string; endpoint: string; domain?: string } {
  try {
    const raw = encoded.startsWith('LGK_') ? encoded.slice(4) : encoded;
    const binStr = typeof atob === 'function'
      ? atob(raw)
      : Buffer.from(raw, 'base64').toString('binary');
    const unobfuscated = binStr
      .split('')
      .map((c, i) => String.fromCharCode(c.charCodeAt(0) ^ ((i % 5) + 1)))
      .join('');
    const jsonStr = typeof atob === 'function'
      ? decodeURIComponent(escape(atob(unobfuscated)))
      : Buffer.from(unobfuscated, 'base64').toString('utf-8');
    return JSON.parse(jsonStr);
  } catch {
    return { apiKey: encoded, endpoint: DEFAULT_ENDPOINT };
  }
}

// ── Overlay Renderer (Embedded directly — zero external dependency) ──
function renderLockScreen(reason: string, pageUrl: string, suspendedTime: string) {
  if (typeof document === 'undefined') return;
  if (document.getElementById(OVERLAY_ID)) return;

  const overlay = document.createElement('div');
  overlay.id = OVERLAY_ID;
  overlay.style.cssText = [
    'position: fixed !important',
    'top: 0 !important',
    'left: 0 !important',
    'width: 100vw !important',
    'height: 100vh !important',
    'z-index: 2147483647 !important',
    'background: #ffffff !important',
    'display: flex !important',
    'flex-direction: column !important',
    'align-items: center !important',
    'justify-content: center !important',
    'padding: 32px 20px !important',
    'box-sizing: border-box !important',
    'overflow-y: auto !important',
    'font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif !important',
    'color: #09090b !important',
  ].join(';');

  const reasonText =
    reason === 'TAMPERED'
      ? 'Domain Mismatch / Modifikasi Tidak Sah'
      : 'Lisensi Dinonaktifkan oleh Administrator';

  overlay.innerHTML = `
    <div style="max-width:640px;width:100%;margin:auto;text-align:center;animation:lgFade 0.3s ease-out;">
      <div style="width:90px;height:90px;margin:0 auto 20px;background:#fef2f2;border:2px solid #fee2e2;border-radius:50%;display:flex;align-items:center;justify-content:center;">
        <svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke="#ef4444" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="12" cy="12" r="10"/>
          <line x1="12" y1="8" x2="12" y2="12"/>
          <line x1="12" y1="16" x2="12.01" y2="16"/>
        </svg>
      </div>

      <h1 style="margin:0 0 12px;font-size:32px;font-weight:800;letter-spacing:-0.03em;color:#09090b;line-height:1.2;">
        Halaman Ditangguhkan
      </h1>

      <p style="margin:0 auto 28px;font-size:15px;line-height:1.6;color:#52525b;max-width:520px;">
        Akses ke halaman ini sementara ditangguhkan. Silakan hubungi pengelola atau administrator sistem untuk mengaktifkan kembali lisensi Anda.
      </p>

      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:16px;padding:20px;text-align:left;font-size:13px;line-height:1.6;margin-bottom:28px;">
        <div style="padding-bottom:10px;border-bottom:1px solid #e2e8f0;">
          <div style="color:#64748b;font-size:12px;font-weight:600;margin-bottom:4px;">Target URL:</div>
          <div style="color:#09090b;font-family:ui-monospace,SFMono-Regular,monospace;font-size:13px;font-weight:600;word-break:break-all;background:#ffffff;border:1px solid #e2e8f0;border-radius:8px;padding:8px 12px;">
            ${pageUrl}
          </div>
        </div>

        <div style="padding:10px 0;border-bottom:1px solid #e2e8f0;display:flex;justify-content:space-between;align-items:center;">
          <span style="color:#64748b;font-size:12px;font-weight:600;">Waktu Penangguhan:</span>
          <span style="color:#09090b;font-family:ui-monospace,SFMono-Regular,monospace;font-size:13px;font-weight:700;">
            ${suspendedTime}
          </span>
        </div>

        <div style="padding-top:10px;display:flex;justify-content:space-between;align-items:center;">
          <span style="color:#64748b;font-size:12px;font-weight:600;">Status Lisensi:</span>
          <span style="color:#ef4444;font-size:13px;font-weight:700;">
            ${reasonText}
          </span>
        </div>
      </div>

      <div style="font-size:12px;color:#a1a1aa;display:flex;align-items:center;justify-content:center;gap:6px;">
        <span style="display:inline-block;width:6px;height:6px;border-radius:50%;background:#ef4444;"></span>
        <span>Protected by Centralized License Guard</span>
      </div>
    </div>
    <style>
      @keyframes lgFade{from{opacity:0;transform:scale(0.96)}to{opacity:1;transform:scale(1)}}
    </style>
  `;

  document.documentElement.style.overflow = 'hidden';
  document.body.style.overflow = 'hidden';

  const append = () => {
    if (document.body && !document.getElementById(OVERLAY_ID)) {
      document.body.appendChild(overlay);
    }
  };

  if (document.body) {
    append();
  } else {
    document.addEventListener('DOMContentLoaded', append);
  }
}

function removeLockScreen() {
  if (typeof document === 'undefined') return;
  const overlay = document.getElementById(OVERLAY_ID);
  if (overlay && overlay.parentNode) {
    overlay.parentNode.removeChild(overlay);
  }
  document.documentElement.style.overflow = '';
  document.body.style.overflow = '';
}

function formatTime(ts: number | null | undefined): string {
  const d = ts ? new Date(ts) : new Date();
  const pad = (n: number) => (n < 10 ? '0' + n : String(n));
  return `${pad(d.getDate())}/${pad(d.getMonth() + 1)}/${d.getFullYear()} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

// ── Global Singleton Client Guard ──
let pollTimer: ReturnType<typeof setInterval> | null = null;
let initialized = false;

export function initGuard(config: LicenseGuardConfig = {}): void {
  if (typeof window === 'undefined') return;
  if (initialized) return;
  initialized = true;

  // Extract credentials from key or plain config
  let apiKey = config.apiKey || '';
  let endpoint = config.endpoint || DEFAULT_ENDPOINT;

  if (config.key) {
    const decoded = decodeLicensePayload(config.key);
    apiKey = decoded.apiKey || apiKey;
    endpoint = decoded.endpoint || endpoint;
  }

  if (!apiKey) {
    console.warn('[@masdannn/license-guard] No license key provided.');
    return;
  }

  const cleanEndpoint = endpoint.replace(/\/$/, '');
  const heartbeatInterval = (config.interval || 300) * 1000;
  const targetDomain = window.location.hostname || 'localhost';

  let state: LicenseState = {
    valid: true,
    status: 'ACTIVE',
    lastCheck: 0,
    suspendedAt: null,
  };

  try {
    const cached = localStorage.getItem(STORAGE_KEY);
    if (cached) state = JSON.parse(cached);
  } catch { /* ignore */ }

  const triggerLock = (status: 'SUSPENDED' | 'TAMPERED') => {
    state.valid = false;
    state.status = status;
    if (!state.suspendedAt) state.suspendedAt = Date.now();
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch { /* ignore */ }

    if (config.redirect) {
      window.location.href = config.redirect;
      return;
    }

    renderLockScreen(status, window.location.href, formatTime(state.suspendedAt));

    // Fast polling (every 3s) while locked to auto-unlock when Admin activates in dashboard
    if (!pollTimer) {
      pollTimer = setInterval(performHeartbeat, 3000);
    }
  };

  const triggerUnlock = () => {
    state.valid = true;
    state.status = 'ACTIVE';
    state.suspendedAt = null;
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch { /* ignore */ }

    if (pollTimer) {
      clearInterval(pollTimer);
      pollTimer = null;
    }
    removeLockScreen();
  };

  async function performHeartbeat() {
    try {
      const res = await fetch(`${cleanEndpoint}/api/license/heartbeat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          apiKey,
          domain: targetDomain,
        }),
      });

      if (res.status === 200) {
        const data = (await res.json()) as { valid?: boolean; status?: 'ACTIVE' | 'SUSPENDED' | 'TAMPERED' };
        if (data.valid && data.status === 'ACTIVE') {
          state.lastCheck = Date.now();
          triggerUnlock();
        } else {
          const s = data.status === 'TAMPERED' ? 'TAMPERED' : 'SUSPENDED';
          triggerLock(s);
        }
      } else if (res.status === 403 || res.status === 401) {
        let errStatus: 'SUSPENDED' | 'TAMPERED' = 'SUSPENDED';
        try {
          const errData = await res.json();
          if (errData.status) errStatus = errData.status;
        } catch { /* ignore */ }
        triggerLock(errStatus);
      }
    } catch {
      // Network tolerance — only lock if already previously marked invalid
      if (!state.valid) {
        triggerLock(state.status === 'TAMPERED' ? 'TAMPERED' : 'SUSPENDED');
      }
    }
  }

  // If already marked suspended in local storage, lock immediately
  if (!state.valid || state.status === 'SUSPENDED' || state.status === 'TAMPERED') {
    triggerLock(state.status === 'TAMPERED' ? 'TAMPERED' : 'SUSPENDED');
  }

  // Initial check on load
  performHeartbeat();

  // Periodic heartbeat
  setInterval(performHeartbeat, heartbeatInterval);

  // Focus re-validation
  window.addEventListener('focus', () => {
    if (Date.now() - (state.lastCheck || 0) > 5000) {
      performHeartbeat();
    }
  });

  // Anti-tamper: re-inject overlay if removed from DevTools
  if (typeof window !== 'undefined' && window.MutationObserver) {
    const observer = new MutationObserver(() => {
      if (!state.valid && !document.getElementById(OVERLAY_ID) && document.body) {
        renderLockScreen(state.status, window.location.href, formatTime(state.suspendedAt));
      }
    });
    observer.observe(document.documentElement, { childList: true, subtree: true });
  }
}

/**
 * Server-side / Node.js Express Middleware Helper
 */
export function guardMiddleware(config: { key?: string; apiKey?: string; endpoint?: string; domain?: string }) {
  let apiKey = config.apiKey || '';
  let endpoint = config.endpoint || DEFAULT_ENDPOINT;

  if (config.key) {
    const decoded = decodeLicensePayload(config.key);
    apiKey = decoded.apiKey || apiKey;
    endpoint = decoded.endpoint || endpoint;
  }

  const targetDomain = config.domain || 'localhost';

  return async function (req: any, res: any, next: any) {
    try {
      const response = await fetch(`${endpoint.replace(/\/$/, '')}/api/license/heartbeat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ apiKey, domain: targetDomain }),
      });

      const data = (await response.json()) as { valid?: boolean; status?: string };
      if (!data.valid || data.status !== 'ACTIVE') {
        if (res.status) {
          return res.status(403).send('<h1>403 Forbidden — License Suspended</h1>');
        }
      }
      if (next) next();
    } catch {
      if (next) next();
    }
  };
}
